<?xml version="1.0" encoding="utf-8"?><Database Name="ut_kids" Class="UtBaseDatoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=RODRIGO;Initial Catalog=ut_kids;User ID=sa" SettingsObjectName="Modelo.Properties.Settings" SettingsPropertyName="ut_kidsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TblDireccion" Member="TblDireccion">
    <Type Name="TblDireccion">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="strestado" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="strmunicipio" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="strcolonia" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="strcalle" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="intcodpost" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="strnumInt" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="strnumExt" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="strreferencias" Type="System.String" DbType="VarChar(400)" CanBeNull="true" />
      <Association Name="TblDireccion_TblPadre" Member="TblPadre" ThisKey="id" OtherKey="idDireccion" Type="TblPadre" />
      <Association Name="TblDireccion_TblProfesor" Member="TblProfesor" ThisKey="id" OtherKey="idDireccion" Type="TblProfesor" />
    </Type>
  </Table>
  <Table Name="dbo.TblNino" Member="TblNino">
    <Type Name="TblNino">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="strNombre" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="strApellidoP" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="strApellidoM" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="intEdad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="strSexo" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="strAlergia" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="idPadre" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idTaller" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TblPadre_TblNino" Member="TblPadre" ThisKey="idPadre" OtherKey="id" Type="TblPadre" IsForeignKey="true" />
      <Association Name="TblTaller_TblNino" Member="TblTaller" ThisKey="idTaller" OtherKey="id" Type="TblTaller" IsForeignKey="true" />
      <Association Name="TblUser_TblNino" Member="TblUser" ThisKey="idUser" OtherKey="id" Type="TblUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TblPadre" Member="TblPadre">
    <Type Name="TblPadre">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="strNombre" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="strApellidoP" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="strApellidoM" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="intEdad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="strSexo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="strCorreo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="bitFoto" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="idDireccion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idTelefono" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TblPadre_TblNino" Member="TblNino" ThisKey="id" OtherKey="idPadre" Type="TblNino" />
      <Association Name="TblDireccion_TblPadre" Member="TblDireccion" ThisKey="idDireccion" OtherKey="id" Type="TblDireccion" IsForeignKey="true" />
      <Association Name="TblTelefono_TblPadre" Member="TblTelefono" ThisKey="idTelefono" OtherKey="id" Type="TblTelefono" IsForeignKey="true" />
      <Association Name="TblUser_TblPadre" Member="TblUser" ThisKey="idUser" OtherKey="id" Type="TblUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TblProfesor" Member="TblProfesor">
    <Type Name="TblProfesor">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="strNombre" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="strApellidoP" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="strApellidoM" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="intEdad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="strSexo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="strCorreo" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="bitFoto" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="strCedula" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="idDireccion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idTelefono" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idTaller" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TblDireccion_TblProfesor" Member="TblDireccion" ThisKey="idDireccion" OtherKey="id" Type="TblDireccion" IsForeignKey="true" />
      <Association Name="TblTaller_TblProfesor" Member="TblTaller" ThisKey="idTaller" OtherKey="id" Type="TblTaller" IsForeignKey="true" />
      <Association Name="TblTelefono_TblProfesor" Member="TblTelefono" ThisKey="idTelefono" OtherKey="id" Type="TblTelefono" IsForeignKey="true" />
      <Association Name="TblUser_TblProfesor" Member="TblUser" ThisKey="idUser" OtherKey="id" Type="TblUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TblTaller" Member="TblTaller">
    <Type Name="TblTaller">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="strNombre" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="strDescripcion" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="strStatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="TblTaller_TblNino" Member="TblNino" ThisKey="id" OtherKey="idTaller" Type="TblNino" />
      <Association Name="TblTaller_TblProfesor" Member="TblProfesor" ThisKey="id" OtherKey="idTaller" Type="TblProfesor" />
    </Type>
  </Table>
  <Table Name="dbo.TblTelefono" Member="TblTelefono">
    <Type Name="TblTelefono">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="strcelular" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="strtelCasa" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="strotro" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="TblTelefono_TblPadre" Member="TblPadre" ThisKey="id" OtherKey="idTelefono" Type="TblPadre" />
      <Association Name="TblTelefono_TblProfesor" Member="TblProfesor" ThisKey="id" OtherKey="idTelefono" Type="TblProfesor" />
    </Type>
  </Table>
  <Table Name="dbo.TblUser" Member="TblUser">
    <Type Name="TblUser">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="strusuario" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="strpass" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="strtipoUsuario" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Association Name="TblUser_TblNino" Member="TblNino" ThisKey="id" OtherKey="idUser" Type="TblNino" />
      <Association Name="TblUser_TblPadre" Member="TblPadre" ThisKey="id" OtherKey="idUser" Type="TblPadre" />
      <Association Name="TblUser_TblProfesor" Member="TblProfesor" ThisKey="id" OtherKey="idUser" Type="TblProfesor" />
    </Type>
  </Table>
</Database>